"""Consts module."""

FENOTEK_URL = "https://backend.fenotek.net"
FENOTEK_LOGIN = "/authenticate"
FENOTEK_VISIONPHONES = "/user/visiophones"
FENOTEK_VISIONPHONE = "/visiophones/{}"
FENOTEK_VISIONPHONE_HOME = "/page/{}/home"
FENOTEK_DRYCONTACTS = "/visiophones/{}/drycontacts"
FENOTEK_PING = "/visiophones/{}/ping"
FENOTEK_DRYCONTACT_ACTIVATE = "/visiophones/{}/drycontacts/{}/activate"
FENOTEK_VISIONPHONE_NOTIFICATIONS = "/visiophones/{}/notifications"
